## 第三章 概率与概率分布

---------------------------------

### 3.1 概率基础知识
#### 3.1.1 一些基本概念

1. 事件 必然事件——U，不可能时间——V，随机事件，简称事件。
2. 频率   
            <center> $W(A)= \frac{m}{n}$ 其中，$0 \le W(A) \le 1$</center>
3. 概率
<center> $P(A)=p=\lim_{n \to \infty}\frac{m}{n}$  其中，$0 \le P(A) \le 1$ </center>

#### 3.1.2 概率的计算

1. 事件的相互关系

    1. 和事件 至少其中一件发生
    2. 积事件 同时发生
    3. 互斥事件 不能同时发生
    4. 对立事件 必发生其一，且不能同时发生
    5. 独立事件 互不关联
    6. 完全事件系 两两互斥，必属其一
    
2.概率计算法则

    1. 加法定理：互斥事件的和事件等于其概率之和。
    2. 乘法定理：独立事件同时发生的概率等于其概率之积。
    
#### 3.1.3 概率分布

+ 离散型随机变量的概率分布
    其概率分布的可以下式表示：
       <center> $P(x=x_i)=p_i (i=1,2,3,···,n)$</center>
       
+ 连续型随机变量的概率分布

    当试验资料为连续型随机变量时，一般通过分组整理成频率分布表。以**频率密度**（`频率/组距`）作直方图，则每个直方图的矩形面积就是该组的频率。当样本容量$n$不断增加，而相应的组距不断减少。当$n$无限大时，频率密度就转化成概率密度，频率分布也就转化成概率分布了。
    
    对于一个连续型随机变量$x$取值于区间[$x_1,x_2$]内的概率为下式所表达：
    <center> $P(x_1 \le x \le x_2)= \int_{x_1}^{x^2} f(x)dx$ </center>
    
#### 3.1.4 大数定理

*贝努里大数定理：当试验在不变的条件下，重复次数n接近无限大时，频率$\frac{m}{n}$与理论概率$p$的差值必定小于一个任意小的正数 $ε$。

*辛钦大数定律：当试验重复次数$n$无限增大时，随机变量的算术平均数$\overline{x}$与总体算术平均数数$\overline{μ}$之间的差值必定小于一个任意小的正数 $ε$。

可以将大数定理通俗地理解为：样本容量越大，赝本统计数与总体参数之差越小。

### 3.2 几种常见的理论分布

随机变量的分布可以用分布函数表述其概率。常见的几种理论分布有：离散型变量的概率分布如`二项分布`、`泊松分布`，连续型变量的概率分布如`正态分布`。

#### 3.2.1 二项分布

生物学中常遇到二项分布，如对于某个性状常可以把资料分成两个类型，彼此构成对立事件。比如种子发芽为事件$A$，概率为$p$，而种子不发芽为事件$\overline{A}$，概率为$q(q=1-p)$.那么$n$次试验中种子发芽事件$A$出现的次数$x$的概率分布函数为：
<center>$P(x)=C_n^xp^xq^{n-x}$  记作$B(n,p)$</center>

理论次数=$NP(x)$

概率累积函数：$F(x)=\sum_{x=0}^iP(x)$

例题1：某小麦品种在田间出现自然变异植株的概率为0.0045，那么期望有0.99的概率获得至少1柱变异植株时至少应调查多少株？

解：由$P(0)=C_n^0p^0q^n=1-0.99$得到$n=1021$

二项分布$B(n,p)$的形状：1.当p值较小且n值不大时，图形是偏倚的。随着n值的增大而变得对称；2.当p值趋于0.5时，分布趋于对称。

二项分布$B(n,p)$的参数：1.总体平均数$μ_x=np$;2.总体标准差$σ_x=\sqrt{npq}$.

二项成数分布的平均数$μ_p=\frac{μ_x}{n}=p$

二项成数分布的标准差$σ_p=\frac{σ_x}{n}=\sqrt{\frac{pq}{n}}$

#### 3.2.2 泊松分布

生物学研究中，很多事件发生的概率很小，而样本容量或试验次数往往很大。此时，二项分布就变成另外一种特殊的分布，即`泊松分布`。

泊松分布也是一种离散型随机变量的分布，其概率函数为：
<center>$P(x)=\frac{e^{-λ}λ^x}{x!}$ 记作$P(λ)$，其中$λ=np, x=0,1,2,·····$</center>

泊松分布的平均数、方差和标准差：$μ=λ, σ^2=λ, σ=\sqrt{λ}$

泊松分布的形状有参数λ决定。当λ较小时，泊松分布是偏倚的，并随着λ的增大而逐渐趋于对称。当λ无限大时，泊松分布逼近正态分布$N(λ,λ)$。而当$λ=20$时，两者已非常接近。

泊松分布在生物学中具有广泛的应用。对于小概率事件，当二项分布的$p<0.1$和$np<5$时可用泊松分布来近似。

例题1用泊松分布来做：$P(0)=e^{-λ}=e^{-np}=0.01, n=\frac{ln 0.01}{-p}=\frac{lg 0.01}{-plge}=1023$

#### 3.2.3 正态分布

正态分布也称高斯分布，是一种连续型随机变量的概率分布。它的分布状态是多数变量围绕在平均值左右，由平均值到分布的两侧，变量数减少。正态分布是一种在统计理论和应用上最重要的分布。实验误差的分布一般服从于正态分布，许多生物学现象的计量资料也近似于正态分布。如果n相当大或p与q基本接近时，二项分布接近于正态分布；当λ较大时，泊松分布也接近于正态分布。

* 正态分布的概率函数：
<center>$f(x)=\frac{1}{σ\sqrt{2π}}e^{-\frac{1}{2}(\frac{x-μ}{σ})^2}$</center>
其中$f(x)$表示某一特定x值出现的概率密度函数值，μ为总体平均数，σ为总体标准差。正态分布记为$N(μ,σ^2)$，表示具有平均数为$μ$，方差为$σ^2$的正态分布。

* 正态分布的特征
    1. 当$x=μ$时，$f(x)$具有最大值$\frac{1}{σ\sqrt{2π}}$;
    2. 当$x-μ$的绝对值相等时，$f(x)$也相等；
    3. $\frac{x-μ}{σ}$的绝对值越大，$f(x)$就越小，且永远不为0；
    4. 正态分布曲线完全由参数μ和σ来决定。μ决定正态分布曲线在x轴上的中心位置，而σ确定正态分布曲线的展开程度。σ越大，曲线展开程度越大（宽胖），反之越小（苗条）。
    5. 正态分布曲线在$x=μ\pm σ$处有一个拐点。曲线通过拐点时改变弯曲方向；
    6. 正态分布的概率密度曲线与渐近线x轴所围成的全部面积为1.
    
* 标准正态分布

对$N(μ,σ^2)$来说不是一条曲线，而是一个曲线系统。令$μ=0, σ^2=1$，则正态分布即可标准化为：
<center>$f(u)=\frac{1}{\sqrt{2π}}e^{-\frac{1}{2}(u^2}$</center>

标准正态分布$N(0,1)$又称为u分布。任何一个正态分布$N(μ,σ^2)$都可以进行标准化：
<center>$u=\frac{x-μ}{σ}$。</center>

其中，u称为标准正态离差，即离开μ具有几个标准差。

标准正态分布的概率累积函数；
<center>$F(u_i)=P(u<u_i)=\int_{-\infty}^{u_i}f(u)du$</center>

对于u落在区间[a,b]的概率为：
<center>$P(a\le u\le b)=\int_a^b\frac{1}{\sqrt{2π}}e^{-\frac{1}{2}u^2}du$</center>

* 正态分布的概率计算

实际需要的各个$F(u)$已有值表，只需将服从正态分布的随机变量x取值区间的上、下限按式$u=\frac{x-μ}{σ}$进行转换，再查表计算即可。

另外，在$μ\pm1.96σ$和$μ\pm2.58σ$范围内已分别包含了95%和99%的变量。因此在计算$|x-μ|>1.96σ$和$|x-μ|>2.58σ$的概率时均为双尾概率，即左尾概率和右尾概率之和。由于两尾概率值经常使用，正态离差u值表列出了两尾概率取某一水平α时的u临界值，即分位数，记为$u_α$，可直接查用。如：$u_0.05=1.96$,$u_0.01=2.5758$。对应于双尾概率，$x\le μ-1.96σ$或$x > μ+1.96σ$的概率称为单尾概率。如，$u_0.05=1.64, u_0.025=1.96, u_0.01=2.33$.

例题：某玉米品种50穗的穗长资料为：$\overline x=15.7,s=1.02cm$，试计算：(1)玉米穗长的95%正常值范围；(2)株高>16cm概率。

解：  
假设玉米穗长服从正态分布，但由于总体平均数μ和总体标准差σ未知，且以样本平均数$\overline x$和样本标准差s来估计μ和σ。  
(1) 两尾概率$\pm u_0.05=\pm1.96=\frac{x-\overline x}{s}, x=13.7cm或17.0cm$;

(2) $u=\frac{16-15.7}{1.02}=0.29, F(0.29)=0.6141, P(x>16.0)=1-0.6141=0.3859$

### 3.3 统计数的分布

生物统计中的一个问题是研究总体与样本的关系，具有两个方向：由总体到样本，研究样本分布及其统计数；由样本到总体，即统计推断。

#### 3.3.1 抽样试验与无偏估计

从总体中抽样必须符合随机的原则。由于无法获取所有可能的样本，解决方法是仅抽取一部分样本进行研究或对小的有限总体进行放回式抽样（重置抽样）。

在统计上，如果所有可能样本的某一统计数的平均数等于总体的相应参数，则称该统计数为总体相应参数的无偏估计值。如在具有变量3,4,5的近似正态分布总体中，以 n=2 作独立的放回式抽样，那么样本平均数、样本方差是无偏估计值，而样品标准差则不是。

#### 3.3.2 样本平均数的分布

从总体中抽出的样本为每一个可能样本，且每个样本中的变量均为随机变量，所以其样本平均数也为随机变量，也形成一定的理论分布，称为样本平均数的概率分布。

样本平均数分布有两个重要参数，样本平均数的平均数$μ_{\overline x}$和样本平均数的方差$σ^2_{\overline x}$.

样本平均数分布具有以下基本性质：(1) 样本平均数分布的平均数等于总体平均数：$μ_{\overline x}=μ$;(2) 样本平均数分布的方差等于总体方差除以单样本容量：$σ^2_{\overline x}=\frac{σ^2}{n}$;进而有样本平均数的标准误差简称平均数标准误的计算式；(3) 如果从正态分布总体$N(μ,σ^2)$进行抽样，其样本平均数$\overline x$是一正态分布$N(μ,\frac{σ^2}{n})$;(4) 如果被抽样总体不是正态总体，但具有平均数μ和方差$σ^2$，当样本容量不断增大时，其样本平均数也越来越接近正态分布$N(μ,\frac{σ^2}{n})$，即是中心极限定理。这个性质对于连续型变量或非连续型变量都能适用。一般只要样本容量大于30，属于大样本，就可应用中心极限定理，认为样本平均数$\overline x$的分布是正态分布，可进行标准化：
<center>$u=\frac{\overline x - μ_{\overline x}}{σ_{\overline x}}=\frac{\overline x-μ}{σ/\sqrt n}$

#### 3.3.3 样本平均数差数的分布

设有两个独立的正态总体，分别进行抽样试验，各得一个样本集合。将来自两个总体的样本平均数进行所有可能的比较，得到样本平均数差数$(\overline x_1 - \overline x_2)$分布，其平均数$μ_{\overline x_1 - \overline x_2}和方差σ^2_{\overline x_1 - \overline x_2}$为：$μ_1-μ_2和\frac{σ^2_1}{n_1}+\frac{σ^2_2}{n_2}$.当$n_1=n_2=n且σ_1=σ_2=σ时，σ^2_{\overline x_1 - \overline x_2}=\frac{σ^2}{n}$.

从两个独立正态总体中抽出的样本平均数差数分布也是正态分布，记作$N(μ_{\overline x_1 - \overline x_2},σ^2_{\overline x_1 - \overline x_2})$.


#### 3.3.4 t 分布
前面计算样本平均数分布和平均数差数分布时，需要总体方差$σ^2$已知或$σ^2$未知但样本容量较大($n \ge 30$)，此时用样本方差$s^2$估计$σ^2$。但在实际研究中经常遇到总体方差未知且样本容量不大的情况，若仍用$s^2$估计$σ^2$，此时$\frac{\overline x - μ}{\frac{s}{\sqrt n}}$就不再服从正态分布了，而是服从自由度为$df=n-1$的t分布，即：
<center>$t=\frac{\overline x - μ}{s_{\overline x}}=\frac{\overline x - μ}{\frac{s}{\sqrt n}}$</center>
其中，$s_{\overline x}$为样本平均数的标准误，是对$σ_{\overline x}$的估计值。

t分布的概率密度函数是：
<center>$f(t)=\frac{Γ(\frac{df+1}{2})}{\sqrt {πdf}Γ(\frac{df}{2})}(1+\frac{t^2}{df})^{\frac{df+1}{2}}$</center>
其中，Γ为伽玛函数，其在实数域上的函数式为:
<center>$\Gamma(x)=\int _0^{+\infty}t^{x-1}e^{-t}dt$</center>

t分布的平均数$\mu_t=0(df>1)$,方差$\sigma_t^2=\frac{df}{df-2}(df>2)$.

t分布具有以下特征：

* t分布曲线是左右对称的，围绕平均数向两侧递降；

* t分布收到自由度df=n-1的制约，每个自由度都有一条t分布曲线；

* 和正态分布相比，t分布的顶部偏低，尾部偏高。当$df \ge 30$时，其曲线接近正态分布。

df=10，P=0.05时记作$t_{0.05(10)}=2.228$.t落于区间$[-t_0.05,+t_0.05]$内的概率为0.95，落于区间$[-t_0.01,+t_0.01]$内的概率为0.99.其中，$t_0.05, t_0.01$分别叫做置信度为5%和1%的t临界值（分位数）。


#### 3.3.5 $\chi^2$ 分布

标准正态离差$u=\frac{x-\mu}{\sigma}$服从$N(0,1)$.如从标准正态分布中抽取k个独立样本，就会得到$u_1^2, u_2^2,···, u_k^2$，则定义它们的和为$\chi^2$，即：
<center>$\chi^2=\sum _{i=1}^k u_i^2=\sum _1^k(\frac{x-\mu}{\sigma})^2$</center>
其中，$\chi^2$的自由度$df=k-1$.$\chi^2$的概率密度函数为：
<center>$f(\chi^2)=\frac{(\chi^2)^{\frac{df}{2}-1}}{2^{\frac{df}{2}}\Gamma(\frac{df}{2})}e^{-\frac{1}{2}\chi^2}$</center>

$\chi^2$分布是连续型变量的分布，每个不同的自由度都有一个相应的卡方分布曲线。卡方分布的特征为：

* $\chi^2$分布于区间[0,+∞)，并且呈反J型的偏斜分布;
* $\chi^2$分布的偏斜度随自由度降低而增大，当df=1时，曲线以纵轴为渐近线；随自由度增大，卡方分布曲线渐趋左右对称，当$df\ge 30$时，已接近正态曲线；

不同自由度下单尾（右尾）概率的$\chi^2$值。如df=2，P=0.05时，$\chi^2=5.9$,记作$\chi^2_{0.05(2)}=5.99$.同理$\chi^2{0.01(2)=9.21}$表示$\chi^2$大于9.21的概率仅有1%。

#### 3.3.6 F 分布

设从一正态分布$N(\mu,\sigma^2)$中随机抽取样本容量为$n_1$和$n_2$两个独立样本，其样本方差分别为$s_1^2$和$s_2^2$，其比值为F：
<center>$F=\frac{s_1^2}{s_2^2}$</center>
此F值具有$s_1^2$的自由度$df_1=n_1-1$和$s_2^2$的自由度$df_2=n_2-1$.

如此进行一系列随机抽样，则所有可能的F值就构成一个F分布。F分布的概率密度函数是由两个独立卡方变量的概率密度所构成的联合概率密度函数，方程为：
<center>$f(F)=\frac{\Gamma(\frac{df_1+df_2}{2})}{\Gamma(\frac{df_1}{2})\Gamma(\frac{df_2}{2})}df_1^{\frac{df_1}{2}}df_2^{\frac{df_2}{2}}\frac{F^{\frac{df_1}{2}-1}}{(df_1F+df_2)^\frac{df_1+df_2}{2}}$</center>

F分布具有以下特征：

* F的取值区间为[0,+∞)；
* F分布的平均数$\mu_F=1$；
* F分布曲线的形状仅决定于$df_1$和$df_2$.在$df_1=1$或2时，F分布曲线呈严重倾斜的反向J型，当$df_1 \ge 3$时转为右偏曲线。

右尾概率值：$F_{0.05(4,10)}=3.48, F_{0.01(4,10)}=5.99$.

```{r}
#rnorm(x,0,1)
#dnorm(x,0,1)
#pnorm(x,0,1)

set.seed(1)
x <- seq(-5,5,length.out=100)
y <- dnorm(x,0,1)
  
plot(x,y,col="red",xlim=c(-5,5),ylim=c(0,1),type='l',
     xaxs="i", yaxs="i",ylab='density',xlab='',
     main="The Normal Density Distribution")

lines(x,dnorm(x,0,0.5),col="green")
lines(x,dnorm(x,0,2),col="blue")
lines(x,dnorm(x,-2,1),col="orange")

legend("topright",legend=paste("m=",c(0,0,0,-2)," sd=", c(1,0.5,2,1)), lwd=1, col=c("red", "green","blue","orange"))
```




