## 第四章 统计推断

---------------------------

本章讨论从样本到总体的方向，根据抽样分布理论由一个样本或一系列样本所得的结果来推断总体的特征，即统计推断问题。

统计推断主要包括假设检验和参数估计两个方面。它们的任务是分析误差产生的原因，确定差异的性质，排除误差干扰，从而对总体的特征做出正确的判断。

### 4.1 假设检验的原理与方法

#### 4.1.1 假设检验的概念

在生物学试验和研究中，当检验一种试验方法的效果、一个品种的优劣、一种药品的疗效等时，所得试验数据往往存在着一定的差异，这种差异是由随机误差引起的，还是由试验处理的效应造成的呢？例如，在同一饲养条件下喂养甲、乙两品系的肉鸡各20只，在二月龄时测得甲系的平均体重为1.5kg，乙系的平均体重1.4kg。甲、乙之间0.1kg的差值，究竟是由于品系原因还是抽样的随机误差所致？此时需要采用假设检验的方法才能做出正确的推断。

假设检验又称显著性检验，就是根据总体的理论分布和小概率原理，对未知或不完全知道的总体提出两种彼此对立的的假设，然后由样本的实际结果，经过一定的计算，做出在一定概率意义上应该接受何种假设的推断。如果抽样结果使小概率事件发生则拒绝假设，如果抽样结果没有使小概率事件发生则接受假设。生物统计学中，一般认为等于或小于0.05或0.01的概率为小概率。

#### 4.1.2 假设检验的步骤

1. 提出假设

首先对总体提出假设，一般作两个彼此独立的假设：一个是无效假设或零假设，记作$H_0$；另一个为备择假设，记作$H_A$。无效假设是直接检验的假设，是对提出的一个假想目标。所谓`无效`是指处理效应与总体参数之间没有真实的差异，试验结果的差异由误差所致。而备择假设是与无效假设相反的一种假设，即认为试验结果中的差异是由总体参数不同所引起的。因此无效假设和备择假设是对立事件。无效假设的两个原则：①无效假设是有意义的；②据此可以算出因抽样误差而获得样本结果的概率。

  1.1 对一个样本平均数的假设 例如，一个样本的平均数$\overline x$来自于一具有平均数$\mu$的总体，可提出：无效假设$H_0$:$\mu=\mu_0$；备择假设$H_A$:$\mu \neq \mu _0$.
  
  1.2 对两个样本平均数相比较的假设 例如，要检验两种制剂的疗效是否相同，两个水稻品种的株高是否一致，成年男女的肺活量是否一样等等。其无效假设为两个样本所属各自总体的平均数是相等的，即这两个总体属于同一总体，两个样本平均数之间的差值由随机误差引起；而备择假设则是认为两个样本所属各自总体的平均数不同，即非同一总体来源。
  
2. 确定显著水平

在进行无效假设和备择假设后，要确定一个否定$H_0$的概率标准，这个概率标准叫做显著水平或概率水平，记作$\alpha$。生物统计学中取α为0.05或0.01两个显著水平。

3. 计算概率

在假设$H_0$正确前提下，根据样本平均数的抽样分布计算出由抽样误差造成的概率。

4. 推断是否接受假设

根据小概率原理做出是否接受$H_0$的判断。小概率原理：如果假设一些条件，并在假设的条件下能够准确的算出事件A出现的概率α为很小，则在假设条件下的n次独立重复试验中，事件A将按预定的概率发生，而在一次试验中几乎不可能发生。如计算的概率大于0.05或0.01则认为不是小概率事件，即$H_0$的假设可能成立，应该接受，同时否定$H_A$;反之则否定$H_0$，接受$H_A$。

通常把等于或小于0.05叫做差异显著标准或差异显著水平概率，而等于或小于0.01叫做差异极显著标准或差异极显著水平概率。一般差异达到显著水平则在资料的右上方标以"\*",差异达到极显著水平则标以"\*\*".
    